export const MODIFICA_NOME = 'modifica_nome'
export const MODIFICA_EMAIL = 'modifica_email'
export const MODIFICA_SENHA = 'modifica_senha'
export const ERRO_CADASTRO = 'erro_cadastro'
export const CADASTRO_SUCESSO = 'cadastro_sucesso'
export const LOGIN_SUCESSO = 'login_sucesso'
export const LOGIN_ERRO = 'login_erro'
export const LOADING_ATIVO = 'loading_login'
